apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kfk
  labels:
    app: kfk
spec:
  serviceName: broker
  replicas: 12
  selector:
    matchLabels:
      app: kfk
  template:
    metadata:
      labels:
        app: kfk
    spec:
      nodeSelector:
        tt-kafka: kafka
      containers:
      - name: kfk
        image: confluentinc/cp-kafka
        env:
        - name: BROKER_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - { name: KAFKA_ZOOKEEPER_CONNECT,                  value: zoo:2181 }
        - { name: KAFKA_INTER_BROKER_LISTENER_NAME,         value: INSIDE }
        - { name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP,     value: INSIDE:PLAINTEXT }
        - { name: KAFKA_ADVERTISED_LISTENERS,               value: INSIDE://$(BROKER_IP):9092 }
---
apiVersion: v1
kind: Service
metadata:
  name: broker
spec:
  clusterIP: None
  selector:
    app: kfk